### ISSUE TITLE
generate.sh: possibly improvement

### ISSUE THREAD

**Issue by labrax** [bio-ontology-research-group/phenomenet-vp#2]
Hi,
I had some problems unzipping the file whole_genome_SNVs_inclAnno.tsv.gz to be used in another step in the generate.sh file. I suggest skipping the intermediary file using a pipe.

generate.sh lines 1, 2:
- gunzip whole_genome_SNVs_inclAnno.tsv.gz
- awk -v OFS='\t' '{print $1,$2,$3,$5,$10,$11,$96,$116}' whole_genome_SNVs_inclAnno.tsv > cadd.txt

+ gunzip -c whole_genome_SNVs_inclAnno.tsv.gz | awk -v OFS='\t' '{print $1,$2,$3,$5,$10,$11,$96,$116}' > cadd.txt

**Comment by imene88** [comment]
@labrax Thank you for your interest in using PVP. We have updated the script as per your recommendation
