### ISSUE TITLE
Error running the sample

### ISSUE THREAD

**Issue by labrax** [bio-ontology-research-group/phenomenet-vp#3]
I was running the samples after installing as described in the GitHub readme and I had this error:
SEVERE: java.lang.ArrayIndexOutOfBoundsException: 9
        at sa.edu.kaust.Classification.toCSV(Classification.java:577)
        at sa.edu.kaust.Main.runTool(Main.java:227)
        at sa.edu.kaust.Main.run(Main.java:152)
        at sa.edu.kaust.Main.main(Main.java:258)

It was caused by a carriage return before the last column on some of the lines in the processed Pfeiffer.vcf.out file. I found an error was caused because of a used "\\r" instead of "\r" in Annotations.java.

Then compiling I had some problems because of missing dependencies, I found some that compiled and added to a patch.

Also, the Gradle versioning is not coherent with the tag in Git, v2.0 has v1.1 in build.gradle - **I did not change it and it is not in the patch file attached**.

Best wishes,
Victor

Patch:
[patch_final.txt](https://github.com/bio-ontology-research-group/phenomenet-vp/files/1975084/patch_final.txt)

I also found other cases with \\<something>, I am not sure if it might be affecting the results somewhere else.
Thank you.

**Comment by imene88** [comment]
@labrax 
Thank you for your valuable contribution. There was a misunderstanding in committing the changes for the build file versioning and required dependencies. We attached your patch and updated the release to enable running the tool from any directory.
